export const FETCH_REGIONS = 'FETCH_REGIONS';
export const FETCH_REGIONS_SUCCESS = 'FETCH_REGIONS_SUCCESS';
export const FETCH_REGIONS_ERROR = 'FETCH_REGIONS_ERROR';

export const FETCH_DEPARTEMENTS = 'FETCH_DEPARTEMENTS';
export const FETCH_DEPARTEMENTS_SUCCESS = 'FETCH_DEPARTEMENTS_SUCCESS';
export const FETCH_DEPARTEMENTS_ERROR = 'FETCH_DEPARTEMENTS_ERROR';

export const FETCH_CITIES = 'FETCH_CITIES';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR';
